import Link from "next/link";

const questions=["¿Qué información necesitamos?","¿Qué evidencia tenemos?","¿Qué protocolo aplica?","¿Quién debe participar?","¿Qué sigue pendiente?","¿Está preparada?"];
const moments=[["Incorporar","¿Tenemos suficiente evidencia para incorporar a este jugador?"],["Promocionar","¿Está preparado para dar el salto al primer equipo?"],["Renovar","¿Qué contexto necesitamos antes de decidir una renovación?"],["Retorno","¿Está disponible la evidencia necesaria para valorar su vuelta?"],["Planificar","¿Qué información necesitamos para preparar la plantilla?"]];
const journey=["Diagnóstico","Diseño","Implantación","Activación","Entrega","Evolución"];

export default function Home(){
 const whatsapp="https://wa.me/34690210722?text=Hola%2C%20me%20gustar%C3%ADa%20conocer%20mejor%20TalentDrop.";
 return <main className="v22-page">
  <header className="site-header"><Link href="/" className="brand-logo" aria-label="TalentDrop"><img src="/brand/talentdrop-logo-light.svg" alt="TalentDrop"/></Link><nav className="nav"><a href="#decision">Qué hacemos</a><Link href="/clubes">Clubes</Link><Link href="/federaciones">Federaciones</Link><Link href="/deportistas">Deportistas</Link><a className="nav-cta" href="#contacto">Contacto</a></nav></header>

  <section className="v22-hero"><div className="v22-hero-bg" style={{backgroundImage:"url('/img/decision-room.jpg')"}}/><div className="v22-hero-copy"><p className="v22-kicker">SPORTS DECISION INFRASTRUCTURE</p><h1>Los clubes no necesitan más información. Necesitan estar preparados para utilizarla.</h1><p>TalentDrop organiza información, evidencia, protocolos y personas alrededor de las decisiones deportivas. Sin sustituir las herramientas del club. Sin sustituir el criterio de sus profesionales.</p><div className="v22-actions"><a className="v22-btn primary" href="#contacto">Solicitar diagnóstico →</a><a className="v22-btn secondary" href="#film">Ver TalentDrop en 60 segundos ▶</a></div></div></section>

  <section id="decision" className="v22-section light"><div className="v22-wrap"><div className="v22-statement"><div><p className="v22-kicker">UNA NUEVA CAPA PARA EL DEPORTE</p><h2 className="v22-title">Tener la información conectada no significa tener una decisión preparada.</h2></div><p className="v22-lead">Scouting, performance, área médica, cantera, vídeo, ERP y documentos ya generan información. TalentDrop trabaja sobre la fragmentación que permanece alrededor de la decisión.</p></div><div className="v22-stage-line"><span>SCOUTING</span><span>·</span><span>PERFORMANCE</span><span>·</span><span>ÁREA MÉDICA</span><span>·</span><span>CANTERA</span><span>·</span><span>VÍDEO</span><span>·</span><span>ERP</span><span>→</span><strong>DECISIÓN DEPORTIVA</strong></div></div></section>

  <section className="v22-editorial"><div className="v22-photo" style={{backgroundImage:"url('/img/club-staff.jpg')"}}/><div className="v22-editorial-copy"><p className="v22-kicker">EL DEPORTE COMO ORGANIZACIÓN</p><h2 className="v22-title">Una decisión reúne conocimiento que vive en lugares distintos.</h2><p>La infraestructura debe hacer visible qué sabemos, qué falta y quién necesita participar antes de decidir.</p></div></section>

  <section className="v22-section white"><div className="v22-wrap"><p className="v22-kicker">LA DECISIÓN COMO PUNTO DE ENCUENTRO</p><h2 className="v22-title">¿Está preparada esta decisión?</h2><div className="v22-questions">{questions.map((q,i)=><div className="v22-question" key={q}><span>{String(i+1).padStart(2,"0")}</span><strong>{q}</strong></div>)}</div><div className="v22-stage-line"><span>Información</span><span>→</span><span>Evidencia</span><span>→</span><span>Contexto</span><span>→</span><span>Readiness</span><span>→</span><strong>Decisión</strong><span>→</span><span>Trazabilidad</span></div></div></section>

  <section id="film" className="v22-section dark"><div className="v22-wrap"><p className="v22-kicker">TALENTDROP · SPORTS DECISION INFRASTRUCTURE</p><h2 className="v22-title">Así funciona una Sports Decision Infrastructure.</h2><p className="v22-lead">Información, evidencia, protocolos y personas conectados alrededor de una decisión deportiva.</p><div className="v22-video-shell"><video controls playsInline preload="metadata" aria-label="TalentDrop — Sports Decision Infrastructure"><source src="/video/talentdrop-decision-infrastructure-web%20(1).mp4" type="video/mp4"/></video></div><p className="v22-lead"><strong style={{color:"#fff"}}>TalentDrop no sustituye las herramientas del club.</strong> Las conecta alrededor de las decisiones deportivas.</p></div></section>

  <section className="v22-section light"><div className="v22-wrap"><p className="v22-kicker">DECISIONES REALES</p><h2 className="v22-title">Diferentes decisiones. La misma necesidad de preparación.</h2><div className="v22-decision-list">{moments.map(([title,text],i)=><div className="v22-decision-row" key={title}><span>{String(i+1).padStart(2,"0")}</span><strong>{title}</strong><p>{text}</p></div>)}</div></div></section>

  <section className="v22-editorial reverse"><div className="v22-photo" style={{backgroundImage:"url('/img/director-athlete-session.jpg')"}}/><div className="v22-editorial-copy"><p className="v22-kicker">PROYECTO LLAVE EN MANO</p><h2 className="v22-title">Diseñada alrededor de la realidad del club.</h2><p>Partimos de cómo trabaja actualmente la organización y diseñamos la infraestructura alrededor de sus decisiones. El modelo de decisión sigue siendo del club.</p></div></section>

  <section className="v22-section ink"><div className="v22-wrap"><p className="v22-kicker">CÓMO TRABAJAMOS</p><h2 className="v22-title">De entender la realidad a dejar una capacidad que evoluciona.</h2><div className="v22-flow">{journey.map((x,i)=><div className="v22-flow-step" key={x}><span>{String(i+1).padStart(2,"0")}</span><strong>{x}</strong></div>)}</div><p className="v22-lead"><strong style={{color:"#fff"}}>TalentDrop aporta la infraestructura.</strong> El modelo de decisión sigue siendo del club.</p></div></section>

  <section className="v22-editorial"><div className="v22-photo" style={{backgroundImage:"url('/img/athlete-journey.jpg')"}}/><div className="v22-editorial-copy lightcopy"><p className="v22-kicker">CONOCIMIENTO INSTITUCIONAL</p><h2 className="v22-title">Cada decisión debería hacer al club un poco más inteligente.</h2><p>La evidencia utilizada, las personas que participaron y el motivo de la decisión pueden permanecer como parte del conocimiento de la organización.</p><div className="v22-stage-line"><span>Decisión</span><span>→</span><span>Trazabilidad</span><span>→</span><span>Conocimiento</span><span>→</span><strong>Siguiente decisión</strong></div></div></section>

  <section id="contacto" className="v22-cta"><div className="v22-cta-copy"><p className="v22-kicker">SIGUIENTE PASO</p><h2 className="v22-title">Empecemos por una decisión real de tu organización.</h2><p>No necesitas cambiar tus sistemas para empezar. Analizamos cómo se prepara hoy la decisión y qué infraestructura necesita alrededor.</p><div className="v22-actions"><a className="v22-btn primary" href="mailto:clubs@talentdrop.es?subject=TalentDrop%20%7C%20Primera%20conversaci%C3%B3n">Hablemos →</a><a className="v22-btn secondary" href={whatsapp} target="_blank" rel="noopener noreferrer">WhatsApp</a></div></div><div className="v22-cta-photo" style={{backgroundImage:"url('/img/youth-training-14-15.jpg')"}}/></section>

  <footer className="footer"><div className="footer-inner"><div><Link href="/" className="footer-logo-v22"><img src="/brand/talentdrop-logo-light.svg" alt="TalentDrop"/></Link><p className="brand-signature">DATA · EVIDENCE · DECISIONS</p><p>Sports Decision Infrastructure</p></div><div className="footer-links"><Link href="/clubes">Clubes</Link><Link href="/federaciones">Federaciones</Link><Link href="/deportistas">Deportistas</Link><a href="mailto:clubs@talentdrop.es">clubs@talentdrop.es</a></div></div></footer>
 </main>;
}
